"""Desktop composition. Routing and profile behavior remain in Window."""
from PyQt6.QtCore import Qt, QSize
from PyQt6.QtGui import QIcon
from PyQt6.QtWidgets import (QButtonGroup, QCheckBox, QComboBox, QFormLayout,
                            QHBoxLayout, QLabel, QLineEdit, QListWidget, QPushButton,
                            QScrollArea, QStackedWidget, QVBoxLayout, QWidget)
from .icons import app_icon
from .widgets import label, panel
from .usage import UsagePage

def build_window(w):
    root = QWidget()
    w.setCentralWidget(root)
    shell = QHBoxLayout(root)
    shell.setContentsMargins(0, 0, 0, 0)
    shell.setSpacing(0)
    sidebar = QWidget()
    sidebar.setObjectName('sidebar')
    sidebar.setFixedWidth(204)
    side = QVBoxLayout(sidebar)
    side.setContentsMargins(14, 22, 14, 18)
    side.setSpacing(8)
    brand = QHBoxLayout()
    icon = QLabel()
    icon.setPixmap(app_icon().pixmap(30, 30))
    brand.addWidget(icon)
    brand.addWidget(label('Net Switch', 'brand'), 1)
    side.addLayout(brand)
    side.addSpacing(25)
    w.overview_button = QPushButton('Overview')
    w.overview_button.setObjectName('nav')
    w.overview_button.setCheckable(True)
    w.overview_button.clicked.connect(w.show_usage)
    side.addWidget(w.overview_button)
    side.addSpacing(23)
    side.addWidget(label('APPLICATIONS', 'eyebrow'))
    w.profiles = QListWidget()
    w.profiles.setIconSize(QSize(22, 22))
    w.profiles.currentItemChanged.connect(w.select)
    w.profiles.itemClicked.connect(lambda _: w.show_apps())
    w.profiles.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
    w.profiles.customContextMenuRequested.connect(w.app_menu)
    side.addWidget(w.profiles, 1)
    w.saved_empty = label('Add your first application\nto choose its network.', 'muted')
    side.addWidget(w.saved_empty)
    side.addWidget(label('CONNECTIONS', 'eyebrow'))
    w.network_summary = label('', 'muted')
    side.addWidget(w.network_summary)
    w.default_summary = label('', 'muted')
    side.addWidget(w.default_summary)
    side.addSpacing(12)
    settings = QPushButton('Network settings')
    settings.setObjectName('ghost')
    settings.clicked.connect(w.open_settings)
    side.addWidget(settings)
    shell.addWidget(sidebar)

    workspace = QWidget()
    main = QVBoxLayout(workspace)
    main.setContentsMargins(0, 0, 0, 0)
    main.setSpacing(0)
    topbar = QWidget()
    topbar.setObjectName('topbar')
    topbar.setFixedHeight(64)
    top = QHBoxLayout(topbar)
    top.setContentsMargins(30, 0, 30, 0)
    w.breadcrumb = label('Overview', 'heading')
    top.addWidget(w.breadcrumb, 1)
    add = QPushButton('+  Add application')
    add.setObjectName('primary')
    add.clicked.connect(w.choose_app)
    top.addWidget(add)
    main.addWidget(topbar)
    w.pages = QStackedWidget()
    editor = QWidget()
    editor_layout = QVBoxLayout(editor)
    editor_layout.setContentsMargins(0, 0, 0, 0)
    editor_layout.setSpacing(0)
    scroll = QScrollArea()
    scroll.setWidgetResizable(True)
    content = QWidget()
    scroll.setWidget(content)
    flow = QVBoxLayout(content)
    flow.setContentsMargins(30, 20, 30, 16)
    flow.setSpacing(12)
    flow.addWidget(label('App routing', 'title'))
    flow.addWidget(label('Choose how this application connects.', 'muted'))
    w.install = QPushButton('Install routing service')
    w.install.clicked.connect(lambda: w.invoke(['install-system'], 'Routing service installed.'))
    w.install.hide()
    flow.addWidget(w.install)
    app_panel, app_layout = panel()
    app_row = QHBoxLayout()
    w.app_icon = QLabel()
    w.app_icon.setFixedSize(40, 40)
    w.app_icon.setPixmap(QIcon.fromTheme('application-x-executable').pixmap(32, 32))
    app_row.addWidget(w.app_icon)
    app_text = QVBoxLayout()
    app_text.setSpacing(4)
    w.app_title = label('Choose an application', 'heading')
    app_text.addWidget(w.app_title)
    w.app_hint = label('Browse installed apps and games.', 'muted')
    app_text.addWidget(w.app_hint)
    app_row.addLayout(app_text, 1)
    choose = QPushButton('Change')
    choose.clicked.connect(w.choose_app)
    app_row.addWidget(choose)
    app_layout.addLayout(app_row)
    flow.addWidget(app_panel)

    network_panel, network_layout = panel()
    network_layout.addWidget(label('Preferred connection', 'heading'))
    w.network_row = QHBoxLayout()
    w.network_row.setSpacing(10)
    w.network_group = QButtonGroup(w)
    w.network_group.buttonClicked.connect(w.network_clicked)
    network_layout.addLayout(w.network_row)
    w.fallback = QCheckBox('Use the other network if internet stops working')
    w.fallback.stateChanged.connect(w.update_hint)
    network_layout.addWidget(w.fallback)
    w.route_hint = label('', 'muted')
    network_layout.addWidget(w.route_hint)
    flow.addWidget(network_panel)

    behavior, behavior_layout = panel()
    behavior_layout.addWidget(label('How the rule applies', 'heading'))
    w.automatic = QCheckBox('Apply whenever I open this app')
    w.automatic.toggled.connect(w.update_automatic)
    behavior_layout.addWidget(w.automatic)
    w.automatic_reason = label('', 'muted')
    behavior_layout.addWidget(w.automatic_reason)
    w.behavior_hint = label('Save once, then open the app normally from your menu or shortcuts.', 'muted')
    behavior_layout.addWidget(w.behavior_hint)
    flow.addWidget(behavior)
    w.advanced_toggle = QPushButton('Advanced options  ›')
    w.advanced_toggle.setObjectName('ghost')
    w.advanced_toggle.setCheckable(True)
    w.advanced_toggle.toggled.connect(w.toggle_advanced)
    flow.addWidget(w.advanced_toggle, alignment=Qt.AlignmentFlag.AlignLeft)
    w.advanced = QWidget()
    form = QFormLayout(w.advanced)
    form.setContentsMargins(0, 0, 0, 0)
    w.interface = QComboBox()
    w.interface.currentIndexChanged.connect(w.connection_changed)
    w.command = QLineEdit()
    w.command.textEdited.connect(w.custom_command)
    form.addRow('Network adapter', w.interface)
    form.addRow('Launch command', w.command)
    flow.addWidget(w.advanced)
    w.advanced.hide()
    flow.addStretch()
    editor_layout.addWidget(scroll, 1)
    footer = QWidget()
    footer.setObjectName('actionbar')
    actions = QHBoxLayout(footer)
    actions.setContentsMargins(30, 14, 30, 14)
    w.remove_app = QPushButton('Remove app')
    w.remove_app.setObjectName('danger')
    w.remove_app.clicked.connect(lambda: w.delete())
    w.remove_app.hide()
    actions.addWidget(w.remove_app)
    actions.addStretch()
    save = QPushButton('Save changes')
    save.clicked.connect(w.save)
    actions.addWidget(save)
    w.launch_button = QPushButton('Launch app')
    w.launch_button.setObjectName('primary')
    w.launch_button.clicked.connect(w.launch)
    actions.addWidget(w.launch_button)
    editor_layout.addWidget(footer)
    w.pages.addWidget(editor)
    w.usage = UsagePage()
    w.pages.addWidget(w.usage)
    main.addWidget(w.pages, 1)
    w.message = label('', 'muted')
    w.message.setContentsMargins(30, 6, 30, 6)
    w.message.hide()
    main.addWidget(w.message)
    shell.addWidget(workspace, 1)
